.webpack/webpack.lantern.base.js

[NP-45] Scripting a unified yarn deployment of nl-pacs within nl-ohif

[NP-45] Scripting a unified yarn deployment of nl-pacs within nl-ohif

---

.webpack/rules/cssToJavaScript.lantern.js
yarn.lock

[NP-94] Pubnub chat infrastructure setup on nl-pacs

[NP-94] Pubnub chat infrastructure setup on nl-pacs

---

extensions/cornerstone/src/commandsModule.js
extensions/cornerstone/src/init.js
extensions/cornerstone/src/initSeriesLinking.js
modes/longitudinal/src/toolbarButtons.js
platform/core/src/services/ViewerToolsetService/ViewerToolset.js
platform/ui/src/assets/icons/tool-series-linking.svg
platform/ui/src/components/Icon/getIcon.js
platform/ui/src/contextProviders/ViewerToolsetProvider.jsx
platform/viewer/package.json

[NP-52] Series Linking

---

extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
platform/viewer/tailwind.config.js

[NP-131] Change color to signify past (non-selected) exams
[NP-131]: https://new-lantern.atlassian.net/browse/NP-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NP-131] Change color to signify past (non-selected) exams

---

extensions/cornerstone/src/init.js

[NP-130] Cursors

---

.webpack/webpack.lantern.base.js

[NP-145] Resolve build conflicts between Material UI/nl-pacs/OHIF
[NP-145]: https://new-lantern.atlassian.net/browse/NP-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NP-145] Resolve build conflicts between Material UI/nl-pacs/OHIF

---

extensions/cornerstone/src/init.js
platform/core/src/services/HangingProtocolService/HangingProtocolService.js
platform/core/src/services/HangingProtocolService/index.js
platform/core/src/services/ServicesManager.js
yarn.lock

[NP-133] Multi-pane view exits when adding previous study

---

extensions/cornerstone/src/commandsModule.js
extensions/cornerstone/src/initReferenceLines.js

[NP-141] Reference Lines and Crosshairs together breaks crosshairs

---

extensions/default/src/DicomWebDataSource/index.js
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
platform/core/src/classes/MetadataProvider.js

Use postgres/api backend

---

extensions/cornerstone/src/commandsModule.js
extensions/cornerstone/src/tools/NLCrosshairs.js

[NP-162] Fix Crosshairs

---

extensions/cornerstone/src/commandsModule.js
extensions/cornerstone/src/initReferenceLines.js
extensions/cornerstone/src/initSeriesLinking.js

show angleInRadians in console

---

platform/viewer/src/components/ViewportGrid.jsx

Check for initial display set

---

extensions/cornerstone/src/OHIFCornerstoneViewport.js
platform/viewer/src/components/ViewportGrid.jsx

[NP-229] Troubleshoot package merging issues
- Refactoring series-instance-linking
- Fixed the staging not working
[NP-229]: https://new-lantern.atlassian.net/browse/NP-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NP-229] Troubleshoot package merging issues

---

extensions/cornerstone/src/OHIFCornerstoneViewport.js
platform/viewer/src/components/ViewportGrid.jsx

[NP-229] Fixing series and instance linking
[NP-229]: https://new-lantern.atlassian.net/browse/NP-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NP-229] Fixing series and instance linking

---

.webpack/webpack.lantern.base.js

webpack add png file loader

---

.eslintrc.json
extensions/default/src/ViewerLayout/index.jsx
platform/core/src/classes/HotkeysManager.js

[NP-25] Fix hotkeys

---

extensions/cornerstone/src/initReferenceLines.js
extensions/default/src/ViewerLayout/index.jsx
platform/ui/src/assets/icons/clipboard.svg
platform/ui/src/components/Header/Header.jsx

Add instance linking button

---

extensions/default/src/DicomWebDataSource/index.js

https://newlantern.slack.com/archives/C02HN8S5H6W/p1651845308391839?thread_ts=1651792610.126079&cid=C02HN8S5H6W

Use mrn instead of patient_id in query params

---

.webpack/rules/cssToJavaScript.lantern.js
yarn.lock

Allow dart-scss use in nl-pacs

Allow dart-scss use in nl-pacs

---

extensions/default/package.json
platform/viewer/package.json
yarn.lock

downgrade react-router to 6.2.1

---

extensions/cornerstone/src/OHIFCornerstoneViewport.js
extensions/cornerstone/src/ViewportOverlay.js
extensions/cornerstone/src/commandsModule.js
extensions/cornerstone/src/init.js
extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking/index.js
extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.js
modes/longitudinal/src/toolbarButtons.js
platform/core/src/services/MeasurementService/MeasurementService.js
platform/core/src/services/ViewerToolsetService/ViewerToolset.js
platform/ui/src/assets/icons/tool-overlay.svg
platform/ui/src/components/Header/Header.jsx
platform/ui/src/components/Icon/getIcon.js
platform/ui/src/components/MeasurementTable/MeasurementItem.js
platform/ui/src/components/MeasurementTable/MeasurementTable.jsx
platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
platform/ui/src/contextProviders/ViewerToolsetProvider.jsx
platform/ui/src/index.js
yarn.lock

feat: NP-292, NP-328, NP-329

---

extensions/cornerstone/src/OHIFCornerstoneViewport.js
platform/viewer/package.json

fix: pubnub build

---

platform/ui/src/components/MeasurementTable/MeasurementItem.js
yarn.lock

fix: measurement item avatar

---

platform/ui/src/components/MeasurementTable/MeasurementItem.js

fix: initial position

---

platform/ui/src/components/MeasurementTable/MeasurementItem.js

fix: color

---

platform/core/src/services/HangingProtocolService/ProtocolEngine.js
platform/viewer/src/routes/Mode/Mode.jsx
yarn.lock

fix: hanging protocol issue

---

platform/ui/src/components/ViewportActionBar/ViewportActionBar.jsx
platform/viewer/src/routes/Mode/Mode.jsx

fix: hanging protocols

---

extensions/measurement-tracking/src/panels/PanelStudyBrowserTracking/requestDisplaySetCreationForStudy.js
platform/core/src/services/HangingProtocolService/ProtocolEngine.js
platform/viewer/src/routes/Mode/Mode.jsx

fix: hanging-protocol

---

extensions/cornerstone/src/init.js
platform/viewer/src/routes/Mode/Mode.jsx
yarn.lock

fix: remove user api call

---

platform/viewer/src/routes/Mode/Mode.jsx

fix: back issue

---

extensions/cornerstone-dicom-sr/src/getSopClassHandlerModule.js
extensions/cornerstone-dicom-sr/src/tools/DICOMSRDisplayTool.ts

* Added support for TID 1410 relationship types
* Added POLYLINE rendering from ladeirarodolfo to PR
* Rolled Dockerfile back to master to make merge easier
* Minor cleanup

feat: Added support for TID 1410 relationship types (#2942)

---

babel.config.js
package.json
yarn.lock

Module resolve on csv relative path

---

package.json
platform/ui/src/components/Dialog/Dialog.jsx
platform/viewer/.webpack/webpack.module.js
platform/viewer/package.json
yarn.lock

1. Fix dialog popup is not showing up when the components passed is undefined. This was working in the old webpack version but not working on the new version.
2. Remove the sourcemap generation and reduce the package size from 30MB into 5MB.

fix dialog popup

---

platform/viewer/.webpack/webpack.module.js
platform/viewer/package.json
yarn.lock

CI Build Fix

---

platform/ui/src/components/Dialog/Dialog.jsx
yarn.lock

Fix modal show error

---

platform/viewer/package.json

Fix the modal show error

---

.drone.jsonnet

update node version for build

---

.drone.jsonnet
yarn.lock

update drone file

---

.webpack/webpack.lantern.base.js
yarn.lock

NL Pacs concurrent running fix

NL Pacs concurrent running fix

---

.webpack/webpack.lantern.base.js

NL Ohif configuration fix for nl-pacs error

NL Ohif configuration fix for nl-pacs error

---

extensions/cornerstone/src/init.js

JIRA Issue: https://new-lantern.atlassian.net/browse/NP-379
Passed user into the author key.

fix: setting user as author

---

.webpack/webpack.lantern.base.js
extensions/default/src/ViewerLayout/ToolbarButtonNestedMenu.jsx
extensions/default/src/getLayoutTemplateModule.js
platform/core/src/classes/HotkeysManager.js
platform/ui/src/components/HotkeyField/HotkeyField.jsx
platform/ui/src/components/HotkeysPreferences/HotkeysPreferences.jsx
platform/ui/src/components/HotkeysPreferences/hotkeysValidators.js
platform/ui/src/components/HotkeysPreferences/utils.js
platform/ui/src/components/Input/Input.jsx
platform/ui/src/components/UserPreferences/UserPreferences.jsx
yarn.lock

Context
I fixed the hotkey validation error. This would occur when resolving an error by changing a hotkey on the item that wasn't displaying the error. I do this by deleting an error if the user resolves an error by changing a hotkey for any tool name. And I also update the error states to include a new toolName in the case that there are multiple duplicate hotkeys.
Changes & Results
I changed HotkeysPreferences.jsx and HotkeysPreferences/utils.js. In utils I changed the validate function to also remove errors that need to be removed. I do this by storing errors in a variable that I manipulate in a helper function called removeErrors(). In the HotkeysPreferences.jsx file I run a check so that all duplicate keys have the same error message. This is important so that they can be removed …

hot key validation errors resolved

---

.webpack/webpack.lantern.base.js
yarn.lock

Fixes the webpack issue as shown in the screenshot:

fix: webpack issues

---

package.json

add build lantern script
